### ISSUE TITLE
Pre-processing test images: normalizing a dataset

### ISSUE THREAD

**Issue by Nova-Scotia** [Evolving-AI-Lab/deep_learning_for_camera_trap_images#8]
Hello there,

I am attempting to train and test a new image classification algorithm using the `R` package `MLWIC` provided in [your recent paper, Tabak et al. 2018](https://www.biorxiv.org/content/10.1101/346809v2). I am an experienced `R` user but do not have experience in `python`. 

I'm trying to process images to ready them for training and testing. In the Tabak et al 2018 paper, it mentions that authors followed methods in your recent publication ([Norouzzadeh et al 2018 - appendix](https://www.pnas.org/content/pnas/suppl/2018/06/04/1719367115.DCSupplemental/pnas.1719367115.sapp.pdf)) 

I have a few questions.

### 1. Am I correct in assuming that the `train` command in `MLWIC` performs "random cropping, horizontal flipping, brightness modification, and contrast modification" to each ***training*** image, as is recommended in both papers? 

There ***is*** code provided within an "L1" folder that does seem to do this, but it's not clear (to me) if this code is leveraged during `MLWIC::train`. I did ask Mikey Tabak about this ([here](https://github.com/mikeyEcology/MLWIC/issues/18)) and I wondered if you could provide any further clarification.

### 2. How is image normalization carried out for the ***test*** dataset?

When I read through the Norouzzadeh et al 2018 appendix (linked above) there is a section on the second page, second paragraph, that states:

>After scaling down the images, we computed the mean and standard deviation of pixel intensities for each color channel separately and then we normalized the images by subtracting the average and dividing by the standard deviation.

I did some reading and found that some authors use the mean and standard deviation of *the entire dataset*, while others use the mean and standard deviation of *each image*. Forgive me this question is naive... (I am, after all, the intended "ecologist-not-data-scientist" audience for the program 😀) - did you use the mean and sd of each image, or of the whole dataset?

I have one final question but I feel that it is more general, so I've posted it on stackoverflow. If you do have time to check it out there, I would be very grateful for your two cents.

https://stackoverflow.com/questions/55306443/normalizing-an-image-in-r-using-mean-and-standard-deviation

**Comment by arashno** [comment]
Hi Nova,
Sorry for my late reply.
Here are my answers:

1. This Python repository performs "random cropping, horizontal flipping, brightness modification, and contrast modification" and as far as I know the R package is just a wrapper around this python repo. Therefore, I believe the R package does the same things.

2. Great question! Both methods are correct and have a little difference in practice. In this repo, I used "per-image-standardization" because Tensorflow had already implemented it. Using the mean and std of the whole dataset is more common in the literature. Moreover, in my experience, using the entire dataset gives slightly better results. 

3. After the standardization, the pixel values should be normally distributed. So [-1.85, 1.85] looks fine to me. When you display an image, and you have negative pixel values, the rendering engine performs a transformation to deal with negative values. I believe this transformation is different from one engine to another. Therefore, I think comparing the processed images visually is not the correct way to check the rightness of the normalization step. I think if you save the numbers into a file and then use the matplotlib library to render the images, you will see the saturated images.

Please let me know if any part of my answer is unclear or you need any further information.

**Comment by Nova-Scotia** [comment]
I read your answer on the weekend and can now come into work on Monday totally focused and ready to continue!! Thanks so much -- this really helps.
