### ISSUE TITLE
Is it a best practice to remove camera software labels on input photos?

### ISSUE THREAD

**Issue by Nova-Scotia** [Evolving-AI-Lab/deep_learning_for_camera_trap_images#9]
My end goal is to train a model with input from a number of different datasets across my study area.

I noticed that some cameras, e.g., *ScoutGuard*, label images just at the bottom left and right - e.g., "ScoutGuard   09.15.2010 17:05:01". The label has a grey background and black text. 

Other cameras, e.g., *Reconyx*, will label images on the top and bottom on the image with a band of black background with white text.

I'm concerned that these areas of the photo will influence the decisions made by the machine learning algorithm. For one, the algorithm might associate one style of labels with certain species more common in that dataset. Secondly, the dark black or bright white in the labels will undoubtedly change the values of the entire image when the image is normalized before entering the machine learning process.

**Did you remove these labels from the images before processing them in the machine learning algorithm you've used here?** 

 I ask because I just figured I would have to do this, but wasn't sure if I was over-thinking it.

**Comment by arashno** [comment]
For our PNAS paper (https://www.pnas.org/content/115/25/E5716/), we removed those labels from the image before resizing them. I simply cut out 100 pixels from the bottom. For our second paper (https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13120) we didn't remove them because when I did some gradient visualization of the network's weights, I found that the network considers those labels as background and does not care about them much. Moreover, when your dataset consists of many different types of cameras removing them could be tricky.

So, I believe you don't need to worry about them but If you need to be 100% sure, you can cut them out before feeding to the network.

**Comment by Nova-Scotia** [comment]
Ok, thanks. I have to do so much per-dataset cleaning before submitting the images that the additional work of cropping wouldn't be much of a hassle.
